nycrecords/gpp-hyrax

- app/controllers/catalog_controller.rb
- app/indexers/nyc_government_publication_indexer.rb
- app/views/records/edit_fields/_date_published.html.erb
This PR adds **Title, Agency, and Date Published** sorting options to the search page.
When saving to Solr, add an extra entry in the document to save Title, Agency, and Date Published as a SSI (String Stored Indexed). By default the custom form fields are saved as TESIM (Text English Stored Indexed Multivalue). Solr is unable sort metadata that is stored as multivalue so we have to create a single value entry in each document. Additionally we have to change the Date Published format from MM/DD/YYYY to YYYY-MM-DD in order to allow for proper alphanumeric sorting.
> Feature/GPP-273: Sort Changes

- config/authorities/agencies.yml
- config/authorities/publication_subjects.yml
Adds following agencies as options:
Note: Commission on Gender Equity (CGE) was already existing 
- Borough Presidents
- Civil Engagement Commission (CEC)
Adds following reports types as options:
- Emergency Preparedness
- Hazard Mitigation
- Accessibility
- Public Health
> Feature/GPP-296: Dropdowns for agencies and subjects

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/models/user.rb
- app/views/layouts/hyrax.html.erb
- app/views/layouts/hyrax/dashboard.html.erb
- config/routes.rb
This PR implements session timeout for authenticated users. 
- Session timeout is handled by the [auto-session-timeout-warning](https://github.com/nycrecords/auto-session-timeout-warning) gem.
- An additional dependency, jquery-ui-rails is required.
- A user's session will automatically timeout after 30 minutes of inactivity. A warning will be displayed 5 minutes before timeout. An AJAX request to `/active` will be sent every 60 seconds to check the server for an active session.
> Feature/GPP-284: Session Timeout for SAML Users

- app/models/concerns/hydra/role_management/user_roles.rb
- app/views/_user_util_links.html.erb
- app/views/hyrax/base/_show_actions.html.erb
- app/views/hyrax/dashboard/show_user.html.erb
- app/views/hyrax/dashboard/sidebar/_activity.html.erb
- app/views/hyrax/dashboard/sidebar/_repository_content.html.erb
- app/views/hyrax/my/works/_default_group.html.erb
- app/views/hyrax/my/works/_facets.html.erb
- app/views/hyrax/my/works/_list_works.html.erb
- app/views/hyrax/my/works/index.html.erb
This PR changes the dashboard to hide certain elements if a user doesn't belong in a certain role. This is mostly done through erb template conditionals such as:
`<% if current_user.admin? %>`
`<% if current_user.library_reviewers? %>`
etc.
Public users are also redirected back to the homepage if they try to access the dashboard. The buttons to go to the dashboard and check notifications are removed from the navbar. This is done by checking if the user `has_nyc_account`.
> Feature/GPP-286: Submitter Dashboard - Redesign

- Gemfile.lock
- app/controllers/sessions_controller.rb
- config/routes.rb
This PR adds the renew_session route required for the latest [commit](https://github.com/nycrecords/auto-session-timeout-warning/commit/ce22d3e7233dbd8ed7d982b4b0eab90b62112d86) of `auto-session-timeout-warning`. This change was made so that a page refresh is not necessary to renew the session timer.
> Feature/GPP-284: Add Renew Session

- app/controllers/concerns/hyrax/works_controller_behavior.rb
- app/models/solr_document.rb
- app/presenters/hyrax/nyc_government_publication_presenter.rb
- app/views/hyrax/base/_attribute_rows.html.erb
- app/views/hyrax/base/_items.html.erb
- app/views/hyrax/base/_member.html.erb
- app/views/hyrax/base/_work_title.erb
- app/views/hyrax/base/show.html.erb
- spec/presenters/hyrax/nyc_government_publication_presenter_spec.rb
- spec/rails_helper.rb
This PR updates the show page with UI changes and display metadata for `NycGovernmentPublication`.
Used https://samvera.github.io/customize-metadata-show-page.html for reference.
- 'shoulda/matchers' and `Shoulda::Matchers.configure` is added to `rails_helper.rb` for [delegate_method](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/independent/delegate_method_matcher.rb).
> Feature/GPP-277: UI updates to record display page

- app/controllers/application_controller.rb
- spec/controllers/application_controller_spec.rb
This PR adds the `after_sign_in_path_for` method to `ApplicationController`, which redirects user to the location that triggered authentication or to the application root.
See devise [documentation](https://github.com/plataformatec/devise/wiki/How-To:-redirect-to-a-specific-page-on-successful-sign-in) for reference.
> Feature/GPP-303: On login, go to homepage

- app/views/hyrax/contact_form/new.html.erb
- config/locales/hyrax.en.yml
Removed contact form and re did page to look like current DSpace GPP contact page.
> Feature/GPP-279: Contact Page Redo

- Gemfile.lock
- app/models/user.rb
- config/initializers/devise.rb
This PR reverts the devise configuration `authentication_keys` value to `[:email]`. The method `user.user_key` is used as the user identifier in places such as roles and notifications. It is defined by first `authentication_keys` value as found [here](https://github.com/projectblacklight/blacklight-access_controls/blob/master/lib/blacklight/access_controls/user.rb#L19-L21).
> Bugfix/GPP-304: Change User Identifier in Adding User to Roles from GUID to Email

- app/services/hyrax/workflow/changes_required_notification.rb
- app/services/hyrax/workflow/pending_review_notification.rb
- config/locales/hyrax.en.yml
Slight changes to the changes required email notification and removed `Mailboxer new message:` from subject line in all emails.
> Feature/OP-281: PO Approval Changes to Emails

- app/assets/javascripts/required_reports.js
- app/views/required_reports/_form.html.erb
Page focus is applied to the error div when an error occurs. This allow the page to scroll up on smaller screens.
> Feature/GPP-293: Add focus to error div on new required report form

- app/views/required_reports/show.html.erb
This PR removes the edit button on and adds word-break to the description field on the `views/required_reports/show.html.erb` page.
> Feature/GPP-293: Remove edit button and add word-break to required_reports show

- app/assets/stylesheets/gpp.scss
- app/views/required_reports/index.html.erb
This PR adds word-wrap to the description column values on the `views/required_reports/index.html.erb` page.
- Add `wrap-text` style class to `gpp.scss` for word-wrap feature.
> Feature/GPP-293: Add word-wrap to description column in required_reports index page

- app/assets/javascripts/required_reports.js
- app/views/required_reports/_form.html.erb
- config/authorities/frequencies.yml
- db/migrate/20191031204401_create_required_reports.rb
- db/schema.rb
This PR changes `start_date` in `required_reports` table to be nullable.
Changes:
- `start_date` in `required_reports` table is nullable.
- Add validation to require "Start date" if "Frequency" is provided on Add Report form.
- Add "Once" to frequencies controlled vocabulary.
> Feature/GPP-338: Change "Start date” to only be required if “Frequency” is provided and add "Once" to frequencies

- app/views/required_reports/index.html.erb
This PR includes changes to the Required Reports table in `views/required_reports/index.html.erb`.
Changes:
- Remove "Frequency", "Frequency integer", "Other frequency description", "Start date", "End date", "Last published date" from table.
- Set column widths.
- Make `required_report.name` a link to show report.
> Feature/GPP-340: Required Reports Table Redesign

- app/controllers/required_reports_controller.rb
- app/models/required_report.rb
- app/models/required_report_due_date.rb
- lib/frequency_calculation.rb
This PR includes the implementation of the `FrequencyCalculation` class to calculate due dates of required reports given the frequency, frequency_integer, start_date and end_date (optional).
- Add `accepts_nested_attributes_for` class method to `RequiredReport` model to allow for saving of child, `required_report_due_dates`, records.
- Add `generate_due_date_attributes` instance method to `RequiredReportDueDate` model to generate attributes to be saved by the parent, `RequiredReport`.
> Feature/GPP-324: Automating Frequency Calculations for RequiredReports Added Via UI

- app/controllers/required_reports_controller.rb
- app/models/required_report_due_date.rb
This PR includes changes to the `RequiredReportsController` and `RequiredReportDueDate` model.
- Type conversion has been moved from the `create` method in the controller to the `generate_due_date_attributes` method in the model.
- Handling for blank `frequency` and `start_date` values is implemented.
> Move parameter type conversions to RequiredReportDueDate model

- app/assets/javascripts/required_reports.js
This PR adds validation to the new required reports form to ensure that if both `start_date` and `end_date` values are provided, the `end_date` must be after the `start_date`.
> Bugfix/GPP-344: New Required Report Form end_date should not be before start_date

- app/controllers/concerns/hyrax/works_controller_behavior.rb
- app/models/deleted_publication.rb
- db/migrate/20200108193343_create_deleted_publications.rb
- db/schema.rb
- spec/models/deleted_publication_spec.rb
This PR creates a table called `deleted_publications` to store the metadata of publications when they are deleted.
Notes:
- Only store metadata of works that are published. Using `curation_concern.suppressed?` to check.
- Stored work metadata before the deletion but created the table row after the work was deleted to ensure the deletion was successful. Is this ok or should we do everything all at once before deletion?
> Feature/GPP-348: Track Deleted Reports

- app/controllers/hyrax/workflow_actions_controller.rb
- app/views/hyrax/base/_form_progress.html.erb
This PR adds the `update_required_report` method in `WorkflowActionsController` to update `required_reports` and `required_report_due_dates` values accordingly based on a workflow action.
- `date_submitted` in `required_report_due_dates` is removed when a library reviewer Request Changes for a work.
- `date_submitted` in `required_report_due_dates` is populated when an agency submitter Request Review for a work.
- "Save" button on submission form is renamed to "Submit".
> Feature/GPP-349: Remove date submitted value on Request Changes

- config/environments/production.rb
This PR sets force_ssl to true in production which enables HSTS and sets secure cookies.
> Feature/GPP-353: T22: Set secure flags on session cookies

- app/controllers/sessions_controller.rb
This PR adds the `Clear-Site-Data` response header on logout. The wildcard derivative is used to clear all types of data.
> Feature/GPP-351: T1539: Clear browser data on user logout

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/views/_user_util_links.html.erb
- config/devise_saml.yml
- config/initializers/controller_override.rb
- config/routes.rb
- db/migrate/20200130152004_add_unique_session_id_to_users.rb
- db/schema.rb
This PR implements a limit the number of concurrent sessions to **1** for each account. 
A migration was generated to add the field `unique_session_id` to `users`. The value of `unique_session_id` is updated every time a user is logged in. 
A `check_concurrent_session` method is created in `ApplicationController` and set as `before_action` to check for if user's current session id is different than `unique_session_id` in the database. If it is different, then the user is redirected to the logout endpoint.
In `session#destroy`, `unique_session_id` is set to `nil` if user logs out manually or is timed out - not if user is logged out from having multiple sessions.
Additional saml configuration changes were made:
- Use sha256 instead of sha1.
- Remove `sign_in` routes as …
> Feature/GPP-357: T429: Limit the number of concurrent sessions for each account

- app/views/catalog/_search_results.html.erb
This PR adds the heading "Search Results" to the search page. Removed the `sr-only` class from original code to make it visible for all and shifted it's position to the top of the results before the previous and next buttons.
> Feature/GPP-307: Added heading for search results on search page

- app/views/report_request_mailer/notice.pdf.erb
- app/workers/report_request_worker.rb
This PR adds an error handler to `ReportRequestWorker` to catch `ActionView::Template::Error` when rendering the PDF.
Additional gsub methods were added to `notice.pdf.erb`.
> Feature/GPP-365: Add Error Handling to ReportRequestWorker

- app/views/layouts/hyrax.html.erb
- app/views/layouts/hyrax/dashboard.html.erb
This PR disables the turbolink for the "Skip to Content" anchor so that focus is maintained on the main content of the page without reloading.
> Disabled Turbolinks for Skip to Content Anchor

- app/assets/stylesheets/gpp.scss
- app/helpers/blacklight/facets_helper_behavior.rb
- app/helpers/blacklight_advanced_search/advanced_helper_behavior.rb
- app/views/_controls.html.erb
- app/views/hyrax/collections/_show_document_list.html.erb
- app/views/hyrax/collections/show.html.erb
- app/views/shared/_ajax_modal.html.erb
This PR fixes accessibility errors raised by the WAVE evaluation tool.
Changes:
- Fixed contrast on navigation links
- Fixed broken aria-labelledby references
- Added aria-label to filter dropdown in advanced search
- Removed empty h2 header
You can test each page by using the Chrome browser extension or pasting the URL in the WAVE site:
- https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh
- https://wave.webaim.org
> Feature/GPP-311: Wave Report Fixes

- app/helpers/hyrax/title_helper.rb
- app/views/advanced/index.html.erb
- app/views/catalog/_search_results.html.erb
- app/views/hyrax/collections/_sort_and_per_page.html.erb
- app/views/hyrax/collections/show.html.erb
- app/views/hyrax/contact_form/new.html.erb
- app/views/hyrax/file_sets/_actions.html.erb
- app/views/kaminari/blacklight_compact/_paginator.html.erb
- app/views/required_reports/index.html.erb
- app/views/required_reports/public_list.html.erb
This PR adds additional changes for 508 accessibility based on Walei's feedback.
1. (Feedback on ) Add an h3 heading before the table. Suggestion to make the label “Displaying X of Y records.”Dev note: We can use the text from the built in blacklight pagination widget. (1 - 10 of 1,983)
**Changes Made: Added tabindex to the "Search Results" heading and the label below it so that can be focused by the keyboard. The label below the heading now has the format, "Displaying X - Y of Z Results"**
2. (Feedback on ) 2 alerts generated from WAVE report:
- One is for justified text.
- The other is for redundant text label
**Changes Made: Removed the `hyc-description` class from collection description so the text is no longer justified (Note that this was for the collection desc added through the …
> Feature/GPP-371: Additional 508 Changes

- lib/mcafee_virus_scan_linux.rb
Run command as root (will require the following entry in `/etc/sudoers`):
```
hyrax	ALL= NOPASSWD: /usr/local/bin/uvscan
```
Recommended to create a specific file for handling users who need to run uvscan (e.g. `/etc/sudoers.d/uvscan`)
This reduces the runtime on Staging from approximately 50 s for a 35 Kb file to 2.89s.
After updating DAT files the following command needs to be run (as root):
```bash
sudo /usr/local/bin/uvscan --decompress
```
This will decompress the DAT files and speed up subsequent scans. 
Corresponding changes are being made to the Ansible playbooks and roles.
> Fix slowness when running uvscan

- app/views/hyrax/collections/_show_document_list.html.erb
- app/views/required_reports/public_list.html.erb
- config/locales/hyrax.en.yml
Changes made:
- Fixed "document" typo in submissions form.
- As per Walei's suggestion, removed caption tag in collection table to reduce confusion for screen reader.
- Added a row heading to each row of the required reports table. When navigating from row to row it will give a helpful description of the data found in the row.
Notes:
- Used index of the required reports list instead of ID because reports added in the future will have  much higher ID numbers which would not make sense in the table since we order by agency.
- To test using voiceover, navigate to the table and use CONTROL + OPTION + UP/DOWN ARROW to move between rows. Use CONTROL + OPTION +LEFT/RIGHT ARROW to move between columns.
> Feature/GPP-371: Additional 508 Changes (Part 2)

- config/initializers/full_text_override.rb
This PR fixes the bug with the hydra-derivates gem (v3.5.0) where the `http_request` method throws **NoMethodError for `use_ssl=' for #<Net::HTTP:Post POST>** when url for solr is https (SSL).
> Bugfix/GPP-380: Derivatives Not Created When SOLR_URL Uses SSL

- app/views/catalog/_index_list_default.html.erb
- lib/blacklight_advanced_search/advanced_search_builder.rb
Fixes Blacklight deprecation warnings
`DEPRECATION WARNING: You provided a String value to IndexPresenter#field_value Provide a Blacklight::Configuration::Field instead. This behavior is deprecated in Blacklight 7. (called from _app_views_catalog__index_list_default_html_erb___310948937101490210_69983573726380 at /opt/hyrax/app/views/catalog/_index_list_default.html.erb:14)`
Caused by line 8 and line 14 in `_index_list_default.html.erb`
Solution suggested in https://github.com/DigitalWPI/digitalwpi/issues/253
Also fixes Blacklight Advanced Search deprecation warning
`DEPRECATION WARNING: search_field_def_for_key is deprecated and will be removed from blacklight 7.x (Use blacklight_config.search_fields[key]). (called from add_advanced_parse_q_to_solr at …
> Hotfix/GPP-403: DEPRECATION WARNING - Blacklight

- app/views/catalog/_index_list_default.html.erb
- lib/blacklight_advanced_search/advanced_search_builder.rb
Fixes Blacklight deprecation warnings
`DEPRECATION WARNING: You provided a String value to IndexPresenter#field_value Provide a Blacklight::Configuration::Field instead. This behavior is deprecated in Blacklight 7. (called from _app_views_catalog__index_list_default_html_erb___310948937101490210_69983573726380 at /opt/hyrax/app/views/catalog/_index_list_default.html.erb:14)`
Caused by line 8 and line 14 in `_index_list_default.html.erb`
Solution suggested in https://github.com/DigitalWPI/digitalwpi/issues/253
Also fixes Blacklight Advanced Search deprecation warning
`DEPRECATION WARNING: search_field_def_for_key is deprecated and will be removed from blacklight 7.x (Use blacklight_config.search_fields[key]). (called from add_advanced_parse_q_to_solr at …
> Bugfix/GPP-403: DEPRECATION WARNING - Blacklight

- app/assets/stylesheets/gpp.scss
- app/views/_user_util_links.html.erb
- app/views/layouts/hyrax.html.erb
- app/views/layouts/hyrax/dashboard.html.erb
- config/application.rb
This PR replaces the i18n functionality for translations with the standard google translate widget.
Notes:
- Styles for widget are based on the NYC Core Framework. https://www1.nyc.gov/assets/doitt/html/nyc-core-framework/index.html
- In `application.rb` force default locale to English using `config.i18n.default_locale = :en`
- Disabled turbolinks globally because it was causing unintended behaviors with the google translate widget. This was done by adding the `data-turbolinks="false"` to the body in `hyrax.html.erb`
> Feature/GPP-384: Replaced i18n locales with google translate widget

- app/assets/stylesheets/gpp.scss
Added a few modifications to the styles to prevent overrides to default app styles
Changes:
- Combined the `container-fluid` and `border-top` class selectors so those styles only apply to the translate section and not other elements using `container-fluid`
- Updated the select styles so that only the select with `.goog-te-combo` will be affected by custom styles
- Calling the Google translate script will automatically apply the following styles to the body tag:
position: relative;
min-height: 100%;
top: 0px;
This interferes with the spacing of the footer on very short (Contact Us) and long (Required Reports) pages. The new styles in the body and html sections will help prevent that.
> Feature/GPP-384: Google translate styles updates

- app/jobs/bulkrax/schedule_relationships_job.rb
- app/mailers/bulk_import_mailer.rb
- app/views/bulk_import_mailer/email.erb
- app/views/bulkrax/importers/show.html.erb
- Addition of zip file name for bulk imports in the show page and email notification
- Cleanup and deletion of imported zip file after successful import
> Add zipfile name to bulk import show page and email notification

- app/controllers/sessions_controller.rb
Remove call to clear cache for NYCID logout.
> Remove cache clearing for NYCID logout

- app/assets/javascripts/agency_contacts.js
- app/assets/stylesheets/gpp.scss
- app/controllers/agency_contacts_controller.rb
- app/controllers/required_reports_controller.rb
- app/decorators/agency_contacts_controller_decorator.rb
- app/helpers/agency_contacts_controller_helper.rb
- app/views/agency_contacts/_email_rows.html.erb
- app/views/agency_contacts/edit.html.erb
- app/views/agency_contacts/index.html.erb
- app/views/hyrax/dashboard/sidebar/_tasks.html.erb
- app/views/required_reports/_form.html.erb
- app/views/required_reports/_required_report.json.jbuilder
- app/views/required_reports/new.html.erb
- app/views/required_reports/public_list.html.erb
- app/views/required_reports/show.html.erb
- config/initializers/assets.rb
- config/locales/hyrax.en.yml
- config/routes.rb
- db/migrate/20250605143718_add_fields_to_required_reports.rb
- db/schema.rb
- spec/controllers/agency_contacts_controller_spec.rb
- spec/decorators/agency_contacts_controller_decorator_spec.rb
- spec/helpers/agency_contacts_controller_helper_spec.rb
- Addition of an agency point of contacts management feature.
- New fields added to the mandated reports creation form.
Run the following after pulling these changes:
```
rails db:migrate
rake assets:precompile   
```
> Add Agency Contacts Management and Enhance Mandated Reports Form
