nycrecords/gpp-hyrax

- app/models/user.rb
- config/application.rb
- config/environments/development.rb
- config/initializers/mailboxer.rb
This PR implements email notifications on top of https://github.com/nycrecords/gpp-hyrax/pull/5.
Used documentation https://samvera.github.io/email_notifications.html as a reference.
The following environment variables must be set in order for emails to work: `SMTP_ADDRESS`, `SMTP_PORT`, and `ACTION_MAILER_HOST`.
> Feature/GPP-261: Create Publication Deposit Workflow (Issues Fix)

- app/forms/hyrax/nyc_government_publication_form.rb
- app/models/nyc_government_publications_metadata.rb
- app/views/records/edit_fields/_date_published.html.erb
- config/locales/hyrax.en.yml
- spec/features/create_nyc_government_publication_spec.rb
Changes:
- Changed Date Issued field to Date Published.
- Added help text to Fiscal Year and Calendar Year to tell users all years prior to 1600 will be defaulted to 1600.
> Feature/GPP-260: QA Fixes

- app/models/nyc_government_publications_metadata.rb
- app/views/hyrax/base/_form_visibility_component.html.erb
This PR sets visibility of work to be public by default.
> Feature/GPP-288: Create Collection not working

- config/authorities/types.yml
Adds following report types as options:
Note: Biennial was already existing
- Reports - Biannual
- Reports - Every 4 Years
- Reports - Every 5 Years
> Feature/GPP-297: Add to report type

- app/assets/stylesheets/gpp.scss
- app/views/hyrax/collections/show.html.erb
This PR contains changes to the homepage UI including enlarging and centering the submit button and removing "Works (#)".
> Feature/GPP-301: More small homepage UI changes

- app/views/hyrax/base/_form.html.erb
- app/views/records/edit_fields/_calendar_year.html.erb
- app/views/records/edit_fields/_date_published.html.erb
- app/views/records/edit_fields/_description.html.erb
- app/views/records/edit_fields/_fiscal_year.html.erb
- app/views/records/edit_fields/_title.html.erb
This PR fixes the issue of javascript not loading on refresh on the New Work form.
> Bugfix/GPP-313: Javascript error with character count and date published on submissions form

- Gemfile
- Gemfile.lock
- app/models/required_report.rb
This PR adds the nilify_blanks gem and implements it for `name` and `agency` in `RequiredReports` model.
> Add nilify_blanks gem

- app/models/agency.rb
- db/migrate/20191106182840_create_agencies.rb
- db/schema.rb
- spec/models/agency_spec.rb
This PR adds the `Agencies` model and migration file.
> Feature/GPP-322: Create Agencies Table

- app/assets/javascripts/required_reports.js
- app/services/frequencies_service.rb
- app/views/layouts/application.html.erb
- app/views/required_reports/_form.html.erb
- app/views/required_reports/index.html.erb
- config/authorities/frequencies.yml
- config/initializers/assets.rb
This PR adds validation to the New Required Report form.
Changes:
- Add new service - `Frequencies`.
- Move javascript from Required Report view to `app/assets`.
> Feature/GPP-293: Validation and Design for Add Required Report Type Form

- app/views/_controls.html.erb
- app/views/_masthead.html.erb
- app/views/catalog/_search_form.html.erb
This PR adds unique aria labels to each navigation region in the header to help screen readers differentiate regions. Also adds additional aria labels to search bar section.
> Feature/GPP-310: Labeling Nav Regions

- app/assets/javascripts/app.js.erb
- app/views/hyrax/collections/_sort_and_per_page.html.erb
This PR changes the default behavior on homepage for the collection sorting filters. Instead of auto reloading whenever a filter is changed, there will be a "Sort Results" button to apply all changes at once.
> Feature/GPP: Homepage Combo Box Accessibility

- app/workers/report_request_worker.rb
- config/authorities/publication_subjects.yml
- db/migrate/20200623202154_add_delinquency_report_id_to_required_report_due_dates.rb
This PR creates a new column `deliquency_report_id` in RequiredReportDueDates and updates the value when a delinquency report is created.
Additional Changes:
- Fix typo in subjects terms.
> Feature/GPP-402: Create delinquency_report_id in RequiredReportDueDates table

- config/authorities/types.yml
This PR adds the following report types:
- Reports - Daily
- Reports - Quarterly
> GPPS-126: Add Report Types

- config/authorities/agencies.yml
This PR adds the following agencies to the agency controlled vocabulary:
- Borough President - Bronx County (BPBX)
- Borough President - Kings County (BPKC)
- Borough President - New York County (BPNY)
- Borough President - Queens County (BPQC)
- Borough President - Richmond County (BPRC)
- NYC Census (Census)
> GPPS-226: Add Agencies

- config/authorities/agencies.yml
> Add New Agencies

- .env.example
- app/controllers/bulkrax/importers_controller.rb
- app/controllers/sessions_controller.rb
- app/jobs/bulkrax/schedule_relationships_job.rb
- app/jobs/create_derivatives_job.rb
- app/mailers/bulk_import_mailer.rb
- app/models/concerns/bulkrax/has_local_processing.rb
- app/views/bulk_import_mailer/email.erb
- config/sidekiq.yml
* Ability to schedule bulkrax imports to time set in .env
* Email notification with summary for completed bulk import
* Tmp file deletion after bulk import
* Derivatives creation job moved to separate sidekiq queue 
* Validation for date_published field in bulkrax import csv
* Session timeout enabled for development
> Add bulkrax scheduling

- .env.example
- app/views/bulkrax/importers/_form.html.erb
- config/initializers/bulkrax.rb
- config/initializers/hyrax.rb
- ENV variables for temp file paths to increase performance
- Bulk imports CSV works limit set to 100
> Add env import paths for performance

- app/models/concerns/bulkrax/has_local_processing.rb
This pull request contains:
- Validation for calendar or fiscal year in a bulk import
- Changes the format of date_published to use the regular submission form format - YYYY-MM-DD
- Refactor of csv fields validations
> Add fiscal_year and calendar_year validation

- app/jobs/bulkrax/schedule_relationships_job.rb
- config/initializers/sidekiq.rb
This PR Contains:
- Retry limit set to 5 for sidekiq worker.
- Code fix for deletion of bulk import zip file and extracted files.
> Sv bulk import temp file deletions

- app/controllers/hyrax/workflow_actions_controller.rb
- Fix to update correct required reports last_published_date when reports exist with no end_date
> Fix required reports last_published_date 

- lib/job_utils.rb
- Rails console function to delete jobs in sidekiq queues
- Rails console function to show jobs in sidekiq queues
> Add console functions to delete and show jobs in sidekiq queues

- app/controllers/concerns/hyrax/works_controller_behavior.rb
- Fix for NoMethodError on 'presenter' in 'show' method by moving the query to after 'presenter' is defined.
> Fix NoMethodError on 'presenter' in 'show' method

- Gemfile
- app/controllers/application_controller.rb
- app/controllers/catalog_controller.rb
- app/controllers/errors_controller.rb
- app/jobs/application_job.rb
- app/views/errors/internal_server_error.html.erb
- app/views/errors/not_found.html.erb
- config/application.rb
- config/initializers/sidekiq.rb
- config/routes.rb
This pr contains:
- General exception handling for the app and solr with redirects to custom error page.
- Removes unused Blacklight routes.
- Adds sidekiq-status gem for better job status monitoring.
> Exception handling

- app/workers/report_request_worker.rb
- lib/tasks/run_report_request_worker_job.rake
This pr contains:
- Rake task to run ReportRequestWorker job
In the terminal run:
```
bundle exec rake run_report_request_worker_job   
```
> Add report request worker job rake task
